-- Supabase/PostgreSQL schema for MMS Gallery
-- Mirrors existing SQLite schema to support full data migration.

CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'student',
  major TEXT,
  year TEXT,
  bio TEXT,
  avatar_url TEXT,
  profession TEXT,
  handle TEXT,
  username TEXT,
  last_username_change TIMESTAMPTZ,
  email_verified INTEGER NOT NULL DEFAULT 1,
  email_verified_at TIMESTAMPTZ,
  linkedin_url TEXT,
  portfolio_url TEXT,
  cover_url TEXT,
  cover_gradient TEXT NOT NULL DEFAULT 'preset_1',
  is_open_to_work INTEGER NOT NULL DEFAULT 0,
  notify_followers INTEGER NOT NULL DEFAULT 1,
  notify_likes INTEGER NOT NULL DEFAULT 1,
  notify_comments INTEGER NOT NULL DEFAULT 1,
  notify_approval INTEGER NOT NULL DEFAULT 1,
  notify_rejection INTEGER NOT NULL DEFAULT 1,
  notify_announcements INTEGER NOT NULL DEFAULT 1,
  privacy_show_email INTEGER NOT NULL DEFAULT 0,
  privacy_show_open_to_work INTEGER NOT NULL DEFAULT 1,
  privacy_allow_followers INTEGER NOT NULL DEFAULT 1,
  privacy_show_follower_count INTEGER NOT NULL DEFAULT 1,
  language_pref TEXT NOT NULL DEFAULT 'en',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_users_username_unique
  ON users (username)
  WHERE username IS NOT NULL AND username <> '';

CREATE TABLE IF NOT EXISTS artworks (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid TEXT UNIQUE NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  category TEXT NOT NULL,
  tags TEXT,
  image_url TEXT,
  file_url TEXT,
  thumbnail_url TEXT,
  file_type TEXT NOT NULL DEFAULT 'image',
  duration_seconds INTEGER,
  status TEXT NOT NULL DEFAULT 'pending',
  featured INTEGER NOT NULL DEFAULT 0,
  views INTEGER NOT NULL DEFAULT 0,
  likes_count INTEGER NOT NULL DEFAULT 0,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS likes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  artwork_id INTEGER NOT NULL REFERENCES artworks(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (user_id, artwork_id)
);

CREATE TABLE IF NOT EXISTS comments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content TEXT NOT NULL,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  artwork_id INTEGER NOT NULL REFERENCES artworks(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS follows (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  follower_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  following_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (follower_id, following_id)
);

CREATE TABLE IF NOT EXISTS notifications (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  type TEXT NOT NULL,
  from_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  artwork_id INTEGER REFERENCES artworks(id) ON DELETE SET NULL,
  is_read INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS feedback (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  subject TEXT NOT NULL,
  message TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS profile_views (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  viewed_user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  viewer_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS email_verification_tokens (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token TEXT UNIQUE NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  used_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS password_reset_tokens (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token TEXT UNIQUE NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  used_at TIMESTAMPTZ
);
